# Generated by Django 4.0.6 on 2022-08-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainprogram',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainprogram',
            name='type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
