# Generated by Django 4.0.6 on 2022-08-24 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_trainprogram_descriptions_trainprogram_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainprogram",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainprogram",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
