# Generated by Django 4.0.6 on 2022-08-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_trainprogram_time_create_trainprogram_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='db.trainprogram'),
        ),
    ]
