# Generated by Django 4.0.6 on 2022-08-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_train_train_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to=settings.AUTH_USER_MODEL),
        ),
    ]
