# Generated by Django 4.0.6 on 2022-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_train_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='train'),
        ),
    ]
